### ISSUE TITLE
Theme : Download Page Overlapping Problem

### ISSUE THREAD

**Issue by Reqrefusion** [marcuspollio/FreeCAD-website#32]
I created an issue because I couldn't solve it quickly. There are similar issues elsewhere. It's annoying.
![resim](https://github.com/user-attachments/assets/1a758d5d-0b18-44f0-a8b9-9b995dd42d92)

**Comment by marcuspollio** [comment]
Thanks for creating this issue.

Could you please list with which screen resolutions this occurs ?

If having a near-square aspect ratio, there are issues indeed, as the cover image on small media ( width <750px) should be near a 2:1 vertical ratio.

**Comment by Reqrefusion** [comment]
It is seen between 450-750 widths.

**Comment by Reqrefusion** [comment]
![resim](https://github.com/user-attachments/assets/4f92e831-da5a-403d-ae36-d98a1daa1137)
Other page to, It is seen between 650-750 widths.
